name: Script Runner

on:
  workflow_call:
    inputs:
      method:
        required: true
        type: string
      description:
        required: true
        type: string

permissions:
  contents: write

jobs:
  runUpdater:
    name: "Run ${{ inputs.method }}"
    runs-on: "ubuntu-latest"

    steps: 
      - name: "Checkout main branch"
        uses: actions/checkout@v4
        with: 
          path: main

      - name: "Checkout publish branch"
        uses: actions/checkout@v4
        with: 
          ref: publish
          path: publish

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: main/package-lock.json

      - name: "Install dependencies"
        run: (cd main && npm i)

      - name: "Run method"
        run: node main/methods/${{ inputs.method }}.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Commit and save changes"
        run: | 
          cd publish
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add api/.
          git commit -m "ci: ${{ inputs.description }}"
          git push
      